[package]
name = "tokio_solicit"
version = "0.0.1"
authors = ["mlalic"]

[dependencies]
log = "0.3.6"
futures = "0.1"
tokio-core = "0.1"
tokio-proto = { git = "https://github.com/tokio-rs/tokio-proto" }
tokio-service = "*"

solicit = { git = "https://github.com/mlalic/solicit" }
